[custom]
;不要随意改变关键字，否则会导致出错
;CNIX规则修改增强版自动选择版

;去广告：不支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：不支持

;设置规则标志位
ruleset=DIRECT,[]GEOSITE,category-ntp
ruleset=DIRECT,[]GEOSITE,category-ddns
ruleset=Ⓜ️微软服务,[]GEOSITE,microsoft@cn
ruleset=Ⓜ️微软服务,[]GEOSITE,onedrive
ruleset=🔰国外流量,[]GEOSITE,github
ruleset=🔰国外流量,[]GEOSITE,microsoft-dev
ruleset=🔰国外流量,[]GEOSITE,microsoft-pki
ruleset=🔰国外流量,[]GEOSITE,bing
ruleset=🔰国外流量,[]GEOSITE,category-pt
ruleset=🔰国外流量,[]GEOSITE,category-porn
ruleset=🔰国外流量,[]GEOSITE,category-dev
ruleset=🔰国外流量,[]GEOIP,facebook,no-resolve
ruleset=🔰国外流量,[]GEOIP,twitter,no-resolve
ruleset=🇦🇮AI,[]GEOSITE,openai
ruleset=🔎Google,[]GEOSITE,google-gemini
ruleset=🇦🇮AI,[]GEOSITE,category-ai-!cn
ruleset=🔎Google,[]GEOSITE,google
ruleset=🔎Google,[]GEOIP,google,no-resolve
ruleset=🔎Google,[]GEOSITE,google-cn
ruleset=✈️Telegram,[]GEOSITE,telegram
ruleset=✈️Telegram,[]GEOIP,telegram,no-resolve
ruleset=📺哔哩哔哩,[]GEOSITE,bilibili
ruleset=🎵TikTok,[]GEOSITE,tiktok
ruleset=🎬国外媒体,[]GEOSITE,category-media
ruleset=🎬国外媒体,[]GEOSITE,disney
ruleset=🎬国外媒体,[]GEOSITE,netflix
ruleset=🎬国外媒体,[]GEOSITE,bahamut
ruleset=🎬国外媒体,[]GEOSITE,spotify
ruleset=🎬国外媒体,[]GEOSITE,hbo
ruleset=🎬国外媒体,[]GEOSITE,primevideo
ruleset=🎬国外媒体,[]GEOSITE,youtube
ruleset=🎬国外媒体,[]GEOSITE,apple-tvplus
ruleset=🎬国外媒体,[]GEOSITE,appledaily
ruleset=🎬国外媒体,[]GEOIP,netflix,no-resolve
ruleset=🔽游戏下载,[]GEOSITE,category-game-platforms-download
ruleset=📟游戏平台,[]GEOSITE,category-games
ruleset=📟游戏平台,[]GEOSITE,xbox
ruleset=📟游戏平台,[]GEOSITE,dmm
ruleset=🍎苹果服务,[]GEOSITE,apple
ruleset=Ⓜ️微软服务,[]GEOSITE,microsoft
ruleset=DIRECT,[]GEOSITE,geolocation-cn
ruleset=DIRECT,[]GEOSITE,CN
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=DIRECT,[]GEOIP,private,no-resolve
ruleset=DIRECT,[]GEOSITE,private
ruleset=⚓️其他流量,[]GEOSITE,test-ipv6
ruleset=⚓️其他流量,[]GEOSITE,ookla-speedtest
ruleset=🌐DNS&配置,[]GEOSITE,category-doh
ruleset=🔰国外流量,[]GEOSITE,geolocation-!cn
ruleset=⚓️其他流量,[]FINAL

custom_proxy_group=🔰国外流量`select`[]♻️自动选择`.*`[]🚀直接连接
custom_proxy_group=♻️自动选择`url-test`.*`https://www.gstatic.com/generate_204`300,,100
custom_proxy_group=⚓️其他流量`select`[]🔰国外流量`[]🚀直接连接`[]♻️自动选择`.*
custom_proxy_group=🌐DNS&配置`select`[]🔰国外流量`[]🚀直接连接`[]♻️自动选择`.*
custom_proxy_group=✈️Telegram`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🔎Google`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🇦🇮AI`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=📺哔哩哔哩`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🎵TikTok`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🎬国外媒体`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🍎苹果服务`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择
custom_proxy_group=Ⓜ️微软服务`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择
custom_proxy_group=📟游戏平台`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🔽游戏下载`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🚀直接连接`select`[]DIRECT


enable_rule_generator=true
overwrite_original_rules=true