[custom]
;不要随意改变关键字，否则会导致出错
;CNIX规则修改增强版自动选择版

;去广告：不支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：不支持

;设置规则标志位
ruleset=🛑广告拦截,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-ads-all.list
ruleset=DIRECT,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-ddns.list
ruleset=DIRECT,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-ntp.list
ruleset=Ⓜ️微软服务,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/microsoft@cn.list
ruleset=Ⓜ️微软服务,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/onedrive.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/github.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/microsoft-dev.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/microsoft-pki.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/bing.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-pt.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-porn.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-dev.list
ruleset=🇦🇮AI,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/openai.list
ruleset=🇦🇮AI,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/google-gemini.list
ruleset=🇦🇮AI,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-ai-!cn.list
ruleset=🔎Google,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/google.list
ruleset=🔎Google,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/google-cn.list
ruleset=✈️Telegram,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/telegram.list
ruleset=📺哔哩哔哩,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/bilibili.list
ruleset=🎵TikTok,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/tiktok.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-media.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/disney.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/netflix.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-media.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/bahamut.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/spotify.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/hbo.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/primevideo.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/youtube.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/apple-tvplus.list
ruleset=🎬国外媒体,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/appledaily.list
ruleset=🔽游戏下载,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-game-platforms-download.list
ruleset=📟游戏平台,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-games.list
ruleset=📟游戏平台,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/xbox.list
ruleset=📟游戏平台,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/dmm.list
ruleset=🍎苹果服务,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/apple.list
ruleset=Ⓜ️微软服务,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/microsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/geolocation-cn.list
ruleset=DIRECT,[]GEOSITE,CN
ruleset=DIRECT,[]GEOIP,CN
ruleset=DIRECT,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/LocalAreaNetwork.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/category-doh.list
ruleset=🔰国外流量,https://raw.githubusercontent.com/SAENE/AirPorts-Rules/main/Clash/geosite/geosite-geolocation-!cn.list
ruleset=⚓️其他流量,[]FINAL

custom_proxy_group=🔰国外流量`select`[]♻️自动选择`.*`[]🚀直接连接
custom_proxy_group=♻️自动选择`url-test`.*`https://www.gstatic.com/generate_204`300,,100
custom_proxy_group=⚓️其他流量`select`[]🔰国外流量`[]🚀直接连接`[]♻️自动选择`.*
custom_proxy_group=🛑广告拦截`select`[]REJECT`[]🚀直接连接`[]🔰国外流量
custom_proxy_group=✈️Telegram`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🔎Google`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🇦🇮AI`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=📺哔哩哔哩`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🎵TikTok`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🎬国外媒体`select`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🍎苹果服务`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择
custom_proxy_group=Ⓜ️微软服务`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择
custom_proxy_group=📟游戏平台`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🔽游戏下载`select`[]🚀直接连接`[]🔰国外流量`[]♻️自动选择`.*
custom_proxy_group=🚀直接连接`select`[]DIRECT


enable_rule_generator=true
overwrite_original_rules=true